### ISSUE TITLE
Missing scripts for online training

### ISSUE THREAD

**Issue by MicheleLeva** [catniplab/vjf#2]
Hello, 
I wanted to try your implementation of the Variational Joint Filtering with Kalman filtering online but it seems that some modules are missing.
In the online.py script the following modules are not imported and I can't find them in the repo: base, observation, decoder, dynamics and metric.
Would you be able to upload these scripts to the repo or tell me where to find them if they are to be downloaded from another source?
Thank you

Michele

**Comment by yuanz271** [comment]
@MicheleLeva Hi Michele. The `VJF` class in the module `model` is the one being used. The `VJF` has only online mode so far as intended for the realtime neuroscience purpose.
The module `online` and `offline` were meant for an offline mode but have not been fully implemented yet.

**Comment by MicheleLeva** [comment]
Thank you, then I'm going to use the `VJF` class in the module `model` as you suggested. 
I wanted to use the `VJF` to train the parameters of a Kalman Filter, is there a particular method I should use to do so? 
I appreciate your help.

**Comment by yuanz271** [comment]
@MicheleLeva I'm not sure if you mean the SSM only or including the inference algorithm as well by Kalman filter. 
For the former, you only need to implement a linear dynamical system to replace the default RBF dynamical system `model.RBFDS` and use a Gaussian likelihood. 
For the latter, you have two options besides the LDS. 1) Learn the SSM only: use the exact Kalman filter inference algorithm for the posterior and optimize the SSM parameters wrt. ELBO. 2) Amortized variational inference: implement a full rank Gaussian recognition model (inference network) if you aim for exactly the same as Kalman filter because only diagonal Gaussian variational posterior has been implemented. It might take effort.

**Comment by MicheleLeva** [comment]
@yuanz271 I understand now, I will see which is the best course of action for my project.
Thank you again for your time and assistance.
